version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=${{ MONGO_DETAILS }}
      - PORT=8080

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb
