version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - NONGNO_DETAILS=${{ MONGO_DETAILS }}

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb
